### ISSUE TITLE
パンフレット作成

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#152]
責任者：中西
目的：集客して損益分岐点を超える

- [x] 着手
期限：10/9
- [x] ビラたたき台作成
期限：10/12
- [x] 内容共有、考えるべきことリスト作成
期限：12:00
- [ ] 文章のディスカッション
期限：10/19
- [ ] ビラ完成
期限：10/19

**Comment by kameiatsushi** [comment]
# 文章作成
## "おもしろい"を基準に
## その学習必要ですか？的な
## 大学入試にも必須
## 講義内容について
## LIFE LAB理念

**Comment by NakanishiHiroki** [comment]
個別フォローアップ
入退室自由で、いつでも講師に質問できる環境で勉強することが出来ます。
《水・金16:00~19:00》《木16:00~21:00》《土9:00~21:00》

格安コース
曜日、時間、教科指定で個別的に指導。
週2コマ・各90分-19000円

**Comment by kameiatsushi** [comment]
# テスト勉強がダメな理由
## 嫌々やると達成感がない
「今日はこれだけやる」と決めて、勉強に取り組むと、終わった後は、疲労と達成感で、「今日はやることをやったから寝よう」となるが、
嫌々ながら勉強をすると終わったあと、「嫌なことを我慢してやったのだから、自分へのご褒美が必要」として、YouTubeなどの娯楽に走ってしまう。
すると、寝不足などを引き起こし悪循環にハマってしまう。

**Comment by kameiatsushi** [comment]
大して勉強してないように見えるのに、妙に成績のいい人っていませんか。
同じように部活して、同じように遊んで、同じように勉強してるのに、なぜか点数が全然違う
そんな人が1人は思い浮かぶのではないでしょうか。
その人たちは何が違うのでしょう？
「頭のデキが違う」などと言いますが、本当にそれだけでしょうか？

実は、テスト勉強に時間をかけている人ほど成績がよくないのです。

**Comment by kameiatsushi** [comment]
# 授業例
- ディスカッション
- ニュース読解
- 調べ学習

**Comment by kameiatsushi** [comment]
# 授業料
## 格安個別
¥12,000-/月4回
¥20,000-/月8回

## 探求コース
¥30,000-/週１コマ + 個別フォロー無制限
¥35,000-/週２コマ + 個別フォロー無制限
