### ISSUE TITLE
生活の見直し

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#339]
責任者：亀井
目的：生産性の向上

- [x] タスク分割
ステータス：着手
- [x] やりたいこと、やるべきことの書き出し（1週間単位）
ステータス：タスク分割が終わったら
期限：
- [x] 重要度、納期を割り振る
ステータス：書き出したら
期限：
- [ ] スケジュールに入れ込む
ステータス：割り振りが終わったら
期限：
- [ ] リカバリー案を書き出す
ステータス：スケジュールに入れたら
期限：
- [ ] 行動計画の完成
ステータス：
期限：12:00

**Comment by kameiatsushi** [comment]
# 亀井

**Comment by NakanishiHiroki** [comment]
# 中西
## やりたいこと
- 生徒主導授業(イベント)

## やるべきこと
- 新谷授業作成
- 文献
- イベント授業作成

**Comment by NakanishiHiroki** [comment]
# 中西
## to do
### 緊急度の低いこと
- ドラム練習
- 読書

**Comment by kameiatsushi** [comment]
曜日 | 月 | 火 | 水 | 木 | 金 | 土 | 日
予定 | 授業@結友, 文賢事前MTG, 小倉スクール | 
納期 |

**Comment by NakanishiHiroki** [comment]
曜日 | 月 | 火 | 水 | 木 | 金 | 土 | 日
--|--|--|--|--|--|--|--
予定 | 授業@結友 | 定例MTG |  |  |  |  |  
納期  | 新谷授業 |  |  |  | 文献 |  |
