### ISSUE TITLE
結友の先生に手紙を書く

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#346]
責任者：
目的：

- [ ] タスク分割
ステータス：未着手
期限：

**Comment by kameiatsushi** [comment]
# 聞きたいこと
- 普段どのように接すればいいか
- 気をつけるべきこと
- 勉強をさせたほうがよいのか
- どのような進路選択があるか
- こどもや保護者にはどのような場所が必要か

**Comment by NakanishiHiroki** [comment]
拝啓

初めてお手紙差し上げます。京都の西陣で学習スペースを運営しておりますLIFE LABです。
LIFE LABでは日中、学校に行くことが出来ない子どもが自分のペースで学習できるように個別に目標を設定して学習の支援をさせていただいております。
今回は結友君の目標や授業内容設定する上で何点かご相談したいことがあり、お手紙を書かせていただきました。

注意の仕方についてのご相談です。
結友君の授業では学校で習った範囲の内容はやっておこうと九九を教えたり、自分で色々と調べものが出来るようにとローマ字を教えたりしています。しかしその際、他に興味のあることが頭に浮かんでいると私たちの話に集中してくれません。授業中、最近ハマっているゲームの話ばかりしているので注意をしようとは思うのですが、集中したくなくて集中していないのか、はたまた集中したくても出来ないのか、どこまでが特性によるものなのかが把握できていないので注意が出来ません。
”こういった特性があるのでそれは注意しても仕方ない”というようなことがあれば教えていただけるとありがたいです。
また、注意に関してではなくても”こういう特性がある為こういう接し方をするべき”ということがあれば教えていただきたいです。

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
近頃、結友君のLIFE LABでの時間の多くがゲームの話をする時間になっています。LIFE LABが生徒にとって自分のしたい話をしたり気ままに遊んだり学んだり出来る場所として価値があるならそれはそれでいいとは思うのですが、結友君に勉強する能力がありそうなのに勉強せず惰性でゲームをしたりYoutubeで動画をだらだらと見ていると講師側としてはもったいないような気もします。(※LIFE LABでは考えてゲームをしたり本当に興味がある動画を集中して見る分には学びとなるのでOKというスタンスなのでネットは見られる環境です)
先生は学校に行けない子どもを沢山見てこられたと思うのですが、そういう子はどういった方法で学習をしているのでしょうか。子どもによって特性は様々だと思いますので、ひとくくりでこうすべきだという答えはないとは思いますが、学校に行けない子の学習についてご意見いただけるとありがたいです。

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー

現在、学校に行けない子どもが三名LIFE LABを利用されているのですが、LIFE LABをより良い空間にするために、保護者や学校に行けない子どもにとって今どのような場所が必要か(LIFE LABがどのような場所であってほしいか)ということについてご意見頂きたいです。

ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
お返事は可能であればメールでお送りいただければありがたいです。
メールアドレス：life.lab.20190401@gmail.com

**Comment by NakanishiHiroki** [comment]
拝啓

初めてお手紙差し上げます。京都の西陣で学習スペースを運営しておりますLIFE LABです。
LIFE LABでは日中、学校に行くことが出来ない子どもが自分のペースで学習できるように個別に目標を設定して学習の支援をさせていただいております。
今回は結友君の目標や授業内容設定する上で何点かご相談したいことがあり、お手紙を書かせていただきました。

まずは注意の仕方についてのご相談です。
結友君の授業では学校で習った範囲の内容はやっておこうと九九を教えたり、自分で色々と調べものが出来るようにとローマ字を教えたりしています。しかしその際、他に興味のあることが頭に浮かんでいると私たちの話に集中してくれません。授業中、最近ハマっているゲームの話ばかりしているので注意をしようとは思うのですが、集中したくなくて集中していないのか、集中したくても出来ないのか、どこまでが特性によるものなのかが把握できていないので注意をしかねています。
”こういった特性があるのでそれは注意しても仕方ない”というようなことがあれば教えていただけるとありがたいです。
また、注意に関してではなくても”こういう特性がある為こういう接し方をするべき”ということがあれば教えていただきたいです。

次に学習の進め方についてのご相談です。近頃、結友君のLIFE LABでの時間の多くがゲームの話をする時間になっています。LIFE LABが生徒にとって自分のしたい話をしたり気ままに遊んだり学んだり出来る場所として価値があるならそれはそれでいいとは思うのですが、結友君に勉強する能力がありそうなのに勉強せず惰性でゲームをしたりYoutubeで動画をだらだらと見ていると講師側としてはもったいないような気もします。(※LIFE LABでは考えてゲームをしたり本当に興味がある動画を集中して見る分には学びとなるのでOKというスタンスなのでネットは見られる環境です)
先生は学校に行けない子どもを沢山見てこられたと思うのですが、そういう子はどういった方法でどのようなペースで学習をしているのでしょうか。子どもによって特性は様々だと思いますので、ひとくくりでこうすべきだという答えはないとは思いますが、学校に行けない子の学習についてご意見いただけるとありがたいです。

最後に、これは結友君に関わらず学校に行けない子全体に関しての質問になるのですが、先生はどういう場所があれば学校に行けない子への助けになると思いますか？
現在、学校に行けない子どもが三名LIFE LABを利用されているのですが、LIFE LABをより良い空間にするために、保護者や学校に行けない子どもにとって今どのような場所が必要か(LIFE LABがどのような場所であってほしいか)ということについてご意見頂きたいです。


お返事は可能であればメールでお送りいただければありがたいです。
メールアドレス：life.lab.20190401@gmail.com

**Comment by kameiatsushi** [comment]
お忙しい中申し訳ありませんが、お返事いただけるとありがたいです

**Comment by kameiatsushi** [comment]
@NakanishiHiroki
