### ISSUE TITLE
20200204 定例MTG

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/tasks#367]
# ルール
- 事前準備をきちんとする
- 前日までに各人議題を確認する
- routineタスクは終わらせておく
- 事前準備が間に合わない場合、前日までに連絡する
- 時間厳守　各項目に関して決められた時間内に結論を出す

# 会議事前準備
- [ ] ２ヶ月先の予定書き込み
- [ ] 1週間のスケジュールの書き込み（事前に書けるもの）

## 2ヶ月先の予定(毎週の予定に関しては直近のものだけ記載)

2月
- 5日(水)
中西不在
- 14日(金)
有馬さんたち来る
- 18日(火)
camechaリリース
つぎの西陣をつくる交流会
- 22日(土)
ボードゲームデー
- 28日(金)
中西不在
マンスリー政治・経済
- 受験シーズン
- 春休み

3月
- 27日(金)
マンスリー政治・経済
- 28日(土)
ボードゲームデー

# 議題
### 前週の授業(10分)
- [内藤結友](https://github.com/life-lab-kyoto/projects/issues/353)
- [ボードゲームデー](https://github.com/life-lab-kyoto/projects/issues/354)
- [火曜](https://github.com/life-lab-kyoto/projects/issues/337)

### 今週の授業
- [火曜]()

## 文賢(5分)
- [今週の報告内容]()
- 次の作業内容を確認

## その他のタスクについて(25分)
- [done](https://github.com/life-lab-kyoto/projects/projects/1#column-5191513)

- [経理](https://github.com/life-lab-kyoto/projects/issues/10)

**Comment by NakanishiHiroki** [comment]
曜日 | 3(月) | 4(火) | 5(水) | 6(木) | 7(金) | 8(土) | 9(日)
--|--|--|--|--|--|--|--
予定 | ×授業@結友/ライブ | 定例MTG/都賀MTG/新谷授業 | ライブ@大阪 |  |  |  |  
やること  |  |  | 新谷授業作成 | 文献/サイトに料金反映 |  |  |  
納期  | 新谷授業作成 |  |  |  |  | 文献 |  

曜日 | 10(月) | 11(火) | 12(水) | 13(木) | 14(金) | 15(土) | 16(日)
--|--|--|--|--|--|--|--
予定 | ×授業@結友/バイト | まさとうくん授業(二月からの予定確認)/定例MTG/新谷授業 |  |  |  |  | 
やること  |  |  |  |  |  |  |  
納期  | 新谷授業作成 |  |  |  |  | 文献 |

**Comment by kameiatsushi** [comment]
# 議事録
星新一のやつは思ったより、受けが悪かった

**Comment by kameiatsushi** [comment]
# やること
- 議論をするときのルールを決める
