### ISSUE TITLE
口語表現チェック

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#411]
口語でしか使わない表現はチェックする

[参考](http://web.mit.edu/kakikotoba/Rules%20for%20Writing%20%20copy.pdf)

**Comment by kameiatsushi** [comment]
# 考察

**Comment by NakanishiHiroki** [comment]
やっぱり やはり
全然
ぜん
全
まった
く
全部 全
すべ
て
一番 最
もっと
も
絶対に 必ず  [決
けっ
して + neg.]
たぶん おそらく
とっても／とても／すごく 非常
ひじょう
に／大変
たいへん
ちょっと 少し
いっぱい／たくさん 多くの N／N が多い  [人：大勢
おおぜい
]
もっと さらに
だんだん 次第
しだい
に／徐々
じょじょ
に
どんどん 急 速
きゅうそく
に
やっと ようやく
いつも 常
つね
に
ちゃんと きちんと／正
ただ
しく
だいたい + # 約
やく
／およそ

**Comment by NakanishiHiroki** [comment]
# 疑問詞
ぎもんし
 (Interrogative)
どうして／なんで なぜ
どんな N どのような N
どっち どちら／いずれ

**Comment by NakanishiHiroki** [comment]
# 指示詞
こっち／そっち／あっち こちら／そちら／あちら
こんな／そんな／あんな このような／そのような／あのような
こんなに／そんなに／あんなに これほど／それほど／あれほど

**Comment by NakanishiHiroki** [comment]
# 接続（助）詞
~けど ~が
~から ~ため
~たら ~ば／~と
でも／だけど しかし／だが
ですから／だから そのため／したがって

**Comment by NakanishiHiroki** [comment]
# その他
~とか や
なんか など
いろんな 色々
いろいろ
な／様々
さまざま
な
~みたい ~のよう
~って(quotation) ~と

**Comment by kameiatsushi** [comment]
WRに投げたのでdone
