### ISSUE TITLE
生徒管理シートにtodolistを作成

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#447]
責任者：亀井
目的：生徒がやるべきことを把握できるようにする
目指す成果：生徒のtodo管理シートを作成

参考：[todo管理雛形](https://torublog.com/spreadsheet-schedule-template/)
[todo管理簡易版](https://docs.google.com/spreadsheets/d/1nceB1ZmGnUDgsTNnMmvszf6pnMB4wyHgbULPmC0h95E/edit#gid=0)

**Comment by kameiatsushi** [comment]
# 必要な項目・機能
- タスク名
- 期限（開始日、終了日）
- タスクのカテゴリ
- 授業出席予定
- 授業予定変更ログ

**Comment by kameiatsushi** [comment]
# 目的例

**Comment by kameiatsushi** [comment]
# シートの要件定義
## メモ
- 期限付きとそうでないタスクを分ける
- 期限が近いかどうかで優先度を分ける

**Comment by lifelabkyoto** [comment]
# 運用
