### ISSUE TITLE
朝日イベント授業案

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#489]
事前MTG：5/25(月) 12:00 - 13:00
イベント実施日：5/30(土) 18:00 - 19:30

対象年齢：小4〜中2
参加予定の生徒：小6、中1、中2, （高2？）

**Comment by kameiatsushi** [comment]
# 授業案
## 甲子園中止について
### 議論テーマ
- 部活ってなんのためにあるの？
- 勝つことは大事か？
- 遊びと勉強と仕事の境界はどこ？

### 理系ネタ
- 球速はどうやって測定しているか（ドップラー効果）
- ボールはなぜ曲がるか（マグヌス効果）
- ストレートを投げる意味を経済学的に考える（ナッシュ均衡）

## テレワークについて
### 議論テーマ
- テレワークにみる労働格差（非正規雇用、ブルーカラー）
- テレワークだと人はさぼるのか
- ワークライフバランス
- リモート授業の注意点
- 学校の存在意義

### 技術系ネタ
- ビデオチャットの原理（音や映像を電気信号に変える）
- VRでリモート授業すると何ができるか

**Comment by kameiatsushi** [comment]
# メモ
### 年上に合わせて話を薦める
年下の子が難しい内容は、先取り学習のモチベーションにつなげるために、「◯年生で習うから知っておくと周りより先取りできる」や「ここは難しいから結論だけ理解して。◯◯の勉強を進めれば理解できるようになる」と言えばよい

###

**Comment by kameiatsushi** [comment]
# 会議で決めたいこと
- 新聞の記事どれにするか
- どうやって入手するか
- 依頼料
- 休校が明けるが、どういう形で継続するか
- 

### LIFE LABの生徒は別でやる

**Comment by kameiatsushi** [comment]
# 議事録（2020/05/25）
オンライン企画できないかという話が朝日でもあがってきたので、それに合わせてやろうとした

最終的にはお金をとれるサービスにしたい

LPみたいなのを作って、そこに色々な授業があって、LIFE LABの授業を受けたい人はそこから入る

ウェブ講座としてやっていくことを考えている
親子で学習するきっかけづくり

テレビ会議でお金をとれるシステムをつくるところがある
インスタライブよりもYouTubeの方がいつでも見れるのでいい

朝日のデータベースに登録されているお客さんにメールできる
広告代理店から告知することも可能？

親子参加を想定している

最初は月1ぐらいのペースで、徐々に増えてきたら月4ぐらいになる？

事前課題を出すために早めに記事と内容を決める

兄弟参加とかで2人が画面に映っても大丈夫か？
保護者が隣にいると発言しにくい？

教材はデジタルか紙か
授業前にCMを流す（朝日が出してる動画、新聞読み方講座ってのがあるみたい）
広告案件をとってくるとか

1週間の試し読みという仕組みを利用する？
2、３回目から新聞をとってもらう

番外編として、クロスワードパズルとかもありかも

紙をスキャンするのは身内では問題ない（本当はウェブ上でやるのはだめかもしれない、有馬さんがokって言ってるからok）

PDFデータを出せる

**Comment by kameiatsushi** [comment]
# 授業案（2020/05/26 議事録）
記事：原則テレワーク

- テレワークできる職業とできない職業
- スナックとかは意外とできてる
- テレワークのメリットデメリット
- 学校へ行ったら

**Comment by NakanishiHiroki** [comment]
![20200522「原則テレワーク」出勤に戻る？_page-0001](https://user-images.githubusercontent.com/49800056/82890723-948ea880-9f87-11ea-8ac5-eb1f20b257b3.jpg)

**Comment by kameiatsushi** [comment]
# メモ
- 全員を当てるのではなく、数人当てていい回答が出たらそこで切る。他に発言したい人がいたら発言してもらう
