### ISSUE TITLE
ABCラジオ出演

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#600]
~収録日：2021/01/28(木) 13:00 〜 13:40~
~放送日：2021/02/01(月) 17:25 〜 17:55~
収録日：2021/03/11(木) 13:00 〜 13:40
放送日：2021/03/15(月) 17:25 〜 17:55

収録場所：朝日放送本社 ABCラジオ・第2スタジオ
大阪市福島区福島1ー1ー30
google map：https://goo.gl/maps/ja7qDZ4tN4UJAqTP7

# 参考資料
- 訂正前
[20210128 ラジオ出演依頼書（亀井敦史様、中西洋輝様）.docx](https://github.com/life-lab-kyoto/tasks/files/5741730/20210128.docx)
- 訂正版
https://docs.google.com/document/d/1-DIjpBSIl6S8l1sJxOvkcCU2hECqL1u6iQJhvPMHDQ0

ラジオ（開始まで数秒ほど待つ）
- https://drive.google.com/file/d/1pYyMje7fku_6y50BM3B1dmhY9mzjNMBY/view
- https://drive.google.com/file/d/1hNL0hJK5TKio4VYQ7y0R65TDe_AypVQo/view

この前食事会で会った人
朝日放送ラジオ株式会社
石城和彦 営業開発部長

**Comment by NakanishiHiroki** [comment]
[有馬さん出演時原稿](https://drive.google.com/file/d/1817FDv4QTWYkTvvkbMzP3D4bgY2RRTJc/view?usp=sharing)

**Comment by NakanishiHiroki** [comment]
# 原案
## 二人のプロフィール
### 亀井
### 中西

## 知識の扉について
### 内容
### 過去回内容
### 4月分内容
### 告知

## LIFE LABについて
### 理念
### 広報
