### ISSUE TITLE
Zoom操作確認自動化

### ISSUE THREAD

**Issue by NakanishiHiroki** [life-lab-kyoto/tasks#603]
# スライド
https://docs.google.com/presentation/d/11AueLM3Ykr2kVFTtnzN1iHV_PZWLgV1PBLjchWuKqq0/edit?usp=sharing
# つくるもの
- 接続テストの説明
- 操作確認のスライド
- 授業の注意点のスライド

**Comment by kameiatsushi** [comment]
# 確認が必要な項目
