### ISSUE TITLE
申請の不備対応

### ISSUE THREAD

**Issue by kameiatsushi** [life-lab-kyoto/tasks#681]
メール：安田さん
https://mail.google.com/mail/u/0/#inbox/FMfcgxwKkRPDwPQNQBFGPXXJqNTLHRxL

メール：apple store 領収書
https://mail.google.com/mail/u/0/#inbox/FMfcgxwJXCKXfHcszdknNxcpHDdFQQCS

ご注文ありがとうございます
https://mail.google.com/mail/u/0/#inbox/FMfcgxwKkblfZFbpggXWswqdMVDRwNfq

## 必要なもの
- [x] 6/29引き落とし、36,677円の明細
- [x] 8/27引き落とし、246,814円の明細
- [x] 9/28引き落とし、41,298円の明細
- [x] yahooクレジットに問合せ
- [x] macの購入内容がわかる請求書など（提出したものは一式としか書いてなくて不足らしい）
- [x] zoomの実施の確認のため、オンライン授業の写真1枚
- [x] 実績報告書を再提出
期限：

- [x] 振込記録の差額を追記
- [x] 8/16〜9/15分のzoom支払の通帳
- [x] PCの支払
期限：2/19(金)

**Comment by lifelabkyoto** [comment]
# 遅延損害金の計算
= 年率14.6% × 遅延日数/365

### 6/29引き落とし分
利用金額：36,677円
支払金額：36,699
差額：22円
支払日：7/6（UFJから振込）
遅延損害金：

### 8/27引き落とし分
利用金額：246,814円
支払金額：247,195円
差額：381円
遅延損害金：

**Comment by lifelabkyoto** [comment]
![スクリーンショット 2021-01-22 14 45 48](https://user-images.githubusercontent.com/62537066/105451871-a3695e80-5cc0-11eb-9691-2b7bc0431d73.png)

**Comment by kameiatsushi** [comment]
# オンライン授業の写真
![スクリーンショット 2021-01-22 14 52 25](https://user-images.githubusercontent.com/38875352/105452398-9862fe00-5cc1-11eb-9de1-c3ad9b162332.png)

[スクリーンショット 2021-01-22 14.52.25.pdf](https://github.com/life-lab-kyoto/tasks/files/5853843/2021-01-22.14.52.25.pdf)

**Comment by kameiatsushi** [comment]
![IMG_20210217_134721](https://user-images.githubusercontent.com/38875352/108157824-fd760c00-7126-11eb-8d06-a47dbf7a1989.jpg)

![IMG_20210217_134713](https://user-images.githubusercontent.com/38875352/108157837-0535b080-7127-11eb-9ee2-44c7d5eccef8.jpg)

**Comment by kameiatsushi** [comment]
[スクリーンショット 2021-02-18 14.07.37 (1).pdf](https://github.com/life-lab-kyoto/tasks/files/6000370/2021-02-18.14.07.37.1.pdf)
